name: API workflow
on: [pull_request]
jobs:
  api-test:
    name: Go test
    runs-on: ubuntu-latest
    steps:
        - name: Checkout source code
          uses: actions/checkout@master
        - name: Go 1.14
          uses: actions/setup-go@v2
          with:
                go-version: '1.14'
        - name: Run test API
          run: |
            cd api
            go test -test.v -test.coverprofile=coverage.out -test.covermode=count ./...
            
  api-lint:
    name: Golangci-lint
    runs-on: ubuntu-latest
    steps:
        - name: Checkout source code
          uses: actions/checkout@master
        - name: Go 1.14
          uses: actions/setup-go@v2
          with:
                go-version: '1.14'
        - name: Setup golang ci-lint
          run: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.7
            echo ::add-path::$HOME/bin
            echo ::add-path::$(go env GOPATH)/bin # for Go projects
        - run: cd api && golangci-lint run